import type { Category } from "@/types/category";

// 패턴은 normalizeMerchant와 동일한 소문자·공백/특수문자 제거 형태입니다.
const rules = ([
  { pattern: "김밥천국", category: "식비" },
  { pattern: "본죽", category: "식비" },
  { pattern: "한솥도시락", category: "식비" },
  { pattern: "맥도날드", category: "식비" },
  { pattern: "버거킹", category: "식비" },
  { pattern: "롯데리아", category: "식비" },
  { pattern: "스타벅스", category: "카페/간식" },
  { pattern: "투썸플레이스", category: "카페/간식" },
  { pattern: "이디야", category: "카페/간식" },
  { pattern: "메가커피", category: "카페/간식" },
  { pattern: "컴포즈커피", category: "카페/간식" },
  { pattern: "파리바게뜨", category: "카페/간식" },
  { pattern: "쿠팡이츠", category: "배달" },
  { pattern: "배달의민족", category: "배달" },
  { pattern: "요기요", category: "배달" },
  { pattern: "땡겨요", category: "배달" },
  { pattern: "배달특급", category: "배달" },
  { pattern: "카카오택시", category: "교통" },
  { pattern: "카카오모빌리티", category: "교통" },
  { pattern: "티머니", category: "교통" },
  { pattern: "코레일", category: "교통" },
  { pattern: "에스알", category: "교통" },
  { pattern: "서울교통공사", category: "교통" },
  { pattern: "한국전력", category: "주거/통신" },
  { pattern: "서울도시가스", category: "주거/통신" },
  { pattern: "삼천리도시가스", category: "주거/통신" },
  { pattern: "에스케이텔레콤", category: "주거/통신" },
  { pattern: "케이티통신", category: "주거/통신" },
  { pattern: "엘지유플러스", category: "주거/통신" },
  { pattern: "넷플릭스", category: "구독/멤버십" },
  { pattern: "유튜브프리미엄", category: "구독/멤버십" },
  { pattern: "쿠팡플레이", category: "구독/멤버십" },
  { pattern: "왓챠", category: "구독/멤버십" },
  { pattern: "티빙", category: "구독/멤버십" },
  { pattern: "멜론", category: "구독/멤버십" },
  { pattern: "지니뮤직", category: "구독/멤버십" },
  { pattern: "스포티파이", category: "구독/멤버십" },
  { pattern: "애플", category: "구독/멤버십" },
  { pattern: "구글", category: "구독/멤버십" },
  { pattern: "netflix", category: "구독/멤버십" },
  { pattern: "youtube프리미엄", category: "구독/멤버십" },
  { pattern: "youtubepremium", category: "구독/멤버십" },
  { pattern: "spotify", category: "구독/멤버십" },
  { pattern: "apple", category: "구독/멤버십" },
  { pattern: "google", category: "구독/멤버십" },
  { pattern: "쿠팡", category: "쇼핑" },
  { pattern: "네이버페이", category: "쇼핑" },
  { pattern: "지마켓", category: "쇼핑" },
  { pattern: "옥션", category: "쇼핑" },
  { pattern: "무신사", category: "쇼핑" },
  { pattern: "다이소", category: "쇼핑" },
  { pattern: "서울아산병원", category: "의료/건강" },
  { pattern: "세브란스병원", category: "의료/건강" },
  { pattern: "삼성서울병원", category: "의료/건강" },
  { pattern: "서울대학교병원", category: "의료/건강" },
  { pattern: "정관장", category: "의료/건강" },
  { pattern: "씨지브이", category: "문화/여가" },
  { pattern: "cgv", category: "문화/여가" },
  { pattern: "롯데시네마", category: "문화/여가" },
  { pattern: "메가박스", category: "문화/여가" },
  { pattern: "예술의전당", category: "문화/여가" },
  { pattern: "롯데월드", category: "문화/여가" },
  { pattern: "교보문고", category: "교육" },
  { pattern: "영풍문고", category: "교육" },
  { pattern: "메가스터디", category: "교육" },
  { pattern: "해커스", category: "교육" },
  { pattern: "대성마이맥", category: "교육" },
  { pattern: "삼성화재", category: "금융/이체" },
  { pattern: "현대해상", category: "금융/이체" },
  { pattern: "디비손해보험", category: "금융/이체" },
  { pattern: "교보생명", category: "금융/이체" },
  { pattern: "한화생명", category: "금융/이체" },
  { pattern: "우체국", category: "기타" },
  { pattern: "대한적십자사", category: "기타" },
  { pattern: "굿네이버스", category: "기타" },
  { pattern: "월드비전", category: "기타" },
  { pattern: "유니세프", category: "기타" },
] satisfies { pattern: string; category: Category }[])
  .sort((left, right) => right.pattern.length - left.pattern.length);

export function classifyByRule(merchantNorm: string): Category | null {
  return rules.find(({ pattern }) => merchantNorm.includes(pattern))?.category ?? null;
}
